services:
  - type: web
    name: telegram-taxi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_TOKEN
        fromSecret: telegram_bot_api_token
    ports:
      - port: 8443
